Rtc 231 move server notifications to protobuffs
jellyfish-dev/elixir_server_sdk pull request #10
Opened 2023-04-28 06:29 UTC by Rados13

2023-04-28 21:20 UTC, mickel8 requested changes
A couple of minor comments but overall looks good :+1:  

If we decided to change proto API, I would consider moving from tuples to structs :thinking:

2023-04-28 21:20 UTC, mickel8 commented on compile_proto.sh
> +  printf "[%i/%i] %s ... " $count $total $file
This always prints [1/1]. Should it?

![image](https://user-images.githubusercontent.com/24651552/235254371-ef4ef93d-2b56-4758-9c19-7017aff38cd9.png)

2023-04-28 21:20 UTC, mickel8 commented on .formatter.exs
> +    ) -- Path.wildcard("lib/protos/**/*.*", match_dot: true)
```suggestion
  inputs: [
    "{lib,test,config}/**/*.{ex,exs}",
    ".formatter.exs",
    "*.exs"
  ],
  import_deps: [:protobuf]
  ```

2023-05-09 13:49 UTC, mickel8 commented on compile_proto.sh
> +  count=$(expr $count + 1)
FYI, you can do `count=$((count + 1))`

https://askubuntu.com/questions/385528/how-to-increment-a-variable-in-bash

2023-05-09 13:49 UTC, mickel8 commented on compile_proto.sh
> +deps="printf find git protoc"
I meant, I don't see why we should check against those commands. Can they be absent?

2023-05-09 13:57 UTC, mickel8 commented on examples/server_socket.exs
> +  def receive_notification() do
I would write this as an anonymous function and save it under `receive_notification`

```elixir
receive_notification = fn ->
 receive do
   ...
  end
  receive_notification.()
end

receive_notification.()
```

2023-05-09 13:57 UTC, mickel8 commented on lib/jellyfish/notifier.ex
> +         content: {_type, %PeerDisconnected{room_id: room_id, peer_id: id}}
I wonder about returning those structs, instead of tuples. Any thoughts?

2023-05-09 15:24 UTC, LVala commented on lib/jellyfish/notifier.ex
> +         content: {_type, %PeerDisconnected{room_id: room_id, peer_id: id}}
Seems like a fine idea.

2023-05-11 10:07 UTC, mickel8 approved these changes

2023-05-11 10:07 UTC, merged