[RTC-275] Allow for subscribing to notifications from a single room
jellyfish-dev/elixir_server_sdk pull request #18
Opened 2023-06-19 10:49 UTC by LVala

2023-06-20 11:39 UTC, roznawsk requested changes
I left some nitpicks.
I am wondering if it would be useful to test other notifications in the tests, other than `PeerConnected`. Can we assume that since this one notification is sent and handled properly, all others will be as well?

2023-06-20 11:39 UTC, roznawsk commented on lib/jellyfish/notifier.ex
> -        {:jellyfish, %Authenticated{}} ->
Why we no longer use the `Authenticated` message?

2023-06-20 11:39 UTC, roznawsk commented on test/jellyfish/notifier_test.exs
> +      token = Application.fetch_env!(:jellyfish_server_sdk, :server_api_token)
I think we can just start notifier without passing any options, it will fetch them from the env anyway.

2023-06-20 11:39 UTC, roznawsk commented on test/jellyfish/notifier_test.exs
> +      {:ok, notifier} = Notifier.start_link()
IMO you can follow this way of starting notifier (i.e. without passing options) in other places.

2023-06-20 11:39 UTC, roznawsk commented on test/jellyfish/notifier_test.exs
>      defstruct [:qwe, :rty]
Is this struct used anywhere?

2023-06-20 11:42 UTC, LVala commented on lib/jellyfish/notifier.ex
> -        {:jellyfish, %Authenticated{}} ->
This message was only received by the process that started the `Notifier` process - a hack to make the `start/1` and `start_link/1` blocking. Nothing changes in the API when it comes to the messages, it wasn't available to the user before either.

2023-06-20 11:48 UTC, LVala commented on test/jellyfish/notifier_test.exs
>      defstruct [:qwe, :rty]
It seems like it isn't.

2023-06-20 11:55 UTC, LVala commented
> I left some nitpicks. I am wondering if it would be useful to test other notifications in the tests, other than `PeerConnected`. Can we assume that since this one notification is sent and handled properly, all others will be as well?

Well, we could, but all of the messages (except for `%Authenticated{}`) are handled by the same function and simply decoded and send further. I guess that if somebody messed with this function and broke it, it could go unnoticed. However, I don't thing we can trigger the other notifications easily (it's `(Room|Component|Peer)Crashed`).

2023-06-20 13:33 UTC, roznawsk approved these changes
Looks great! 🎖️

2023-06-21 07:11 UTC, bblaszkow06 requested changes

2023-06-21 07:24 UTC, LVala commented on lib/jellyfish/notifier.ex
> +  for example `{:jellyfish, %Jellyfish.ServerMessage.RoomCrashed{room_id: "some_id"}}`.
That's exactly what I initially did, although the types of generated structs contain references to types from the `protobuf` library and breaks CI etc. But I'll try to find a workaround.

2023-06-21 07:40 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +      |> then(&put_in(state, [:subscriptions, room_id], &1))
I'd replace that pipe with `update_in`:
```suggestion
      update_in(state.subscriptions[room_id], fn
        nil -> MapSet.new()
        set -> MapSet.put(set, pid)
      end)
```

2023-06-21 07:40 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +      |> then(&Map.put(state, :subscriptions, &1))
```suggestion
      Map.update!(state, :subscriptions, fn subs ->
        Map.new(subs, fn {id, pids} -> {id, MapSet.delete(pids, pid)} end)
      end)
```

2023-06-22 14:40 UTC, bblaszkow06 requested changes

2023-06-22 14:40 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +    WebSockex.cast(notifier, {:unsubscribe, process})
There's one more RC here - the subscriber might have some notifications already queued in its mailbox or may receive it before the notifier processes this message (since it's a cast, not a call)

2023-06-22 14:40 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +    state =
There's one more important thing missing - the notifier should monitor the subscriber and remove it when it goes down

2023-06-23 07:04 UTC, LVala commented on lib/jellyfish/notification.ex
> +  """
I kept it only so the reference in `doc` of `Notifier.subscribe/3` works, but I guess its not really helpful, I'll find a workaround.

2023-06-23 07:16 UTC, LVala commented on lib/jellyfish/notification.ex
> +    @moduledoc "Defines `t:Jellyfish.Notification.RoomCrashed.t/0`."
I was initially going to leave the `moduledoc`s empty, but `credo` is not happy about that. Thb, I just discovered `@moduledoc nil` and the module names and fields are quite self-explanatory.

2023-06-23 07:23 UTC, roznawsk commented on README.md
> +:ok = Jellyfish.Notifier.subscribe(notifier, :all)
I don't think that's a problem. When subscribing to notifications we can always get the room's state to be up to date.

2023-06-23 07:51 UTC, LVala commented on README.md
> +:ok = Jellyfish.Notifier.subscribe(notifier, :all)
I mean, it's a little bit inconvenient, imagine that you created a room, it crashed, and only then you subscribed to notifications. When you query the room state, you'll get that it doesn't exist.

2023-06-23 08:23 UTC, LVala commented on README.md
> +:ok = Jellyfish.Notifier.subscribe(notifier, :all)
The only thing that's comes to my mind is buffering a few of the last messages tho, as the messages that we might lose aren't very frequent (basically only `RoomCrashed`, maybe something like `RoomRemoved` in the future), what do you think @bblaszkow06?

2023-06-23 09:07 UTC, LVala commented on lib/jellyfish/notifier.ex
> +    WebSockex.cast(notifier, {:unsubscribe, process})
`Websockex` API doesn't provide `call` for some reason, besides that, even if we used `call`, I don't see how we can take care of the messages in a mailbox, as we can call the `unsubscribe` for process other than `self()`?
But is this really a problem, I didn't thought of `unsubscribe` as a "after this point you definitely won't get notifications" but rather "tell the notifier to not spam this process anymore", especially as every notification contains `room_id` anyway.

2023-06-23 15:16 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +    WebSockex.cast(notifier, {:unsubscribe, process})
> But is this really a problem, I didn't thought of unsubscribe as a "after this point you definitely won't get notifications" but rather "tell the notifier to not spam this process anymore", especially as every notification contains room_id and unwanted messages can be ignored

Well, the minimal solution would be to document that behaviour and what you thought of it.
Taking one step backwards, the subscription of process other than self seems like something rarely used and if we got rid of that, we could flush the mailbox like [`Process.demonitor/2`](https://hexdocs.pm/elixir/Process.html#demonitor/2)

API-wise it might be surprising to receive the messages you've just unsubscribed from.

Going even further back, I'm not sure the unsubscribe is needed at all. Most of the time the combination of `subscribe` and monitoring the subscriber will be enough.

To sum up, I'd probably remove the unsubscription in favour of monitoring, then if needed added the unsubscribe for the calling process with flush option and then if necessary add an option to unsub other process

2023-06-27 12:07 UTC, LVala commented on .gitmodules
> +	branch = per-room-notifications
This is going to be reverted before merging, also tests doesn't pass because they require new Jellyfish image from PR which hasn't been merged yet.

2023-06-27 12:41 UTC, LVala commented on lib/jellyfish/notifier.ex
> +    state = put_in(state.pending_subscriptions[room_id], pid)
I just noticed that this has to be fixed, multiple processes can subscribe to the same `room_id`.

2023-06-27 17:06 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +      |> Enum.map(&%Component{id: &1.id, type: from_proto_type(&1.type)})
IMO these should be implemented in Peer and Component, i.e.

```suggestion
      |> Enum.map(&Peer.from_proto/1)

    components =
      msg.components
      |> Enum.map(&Component.from_proto/1)
```

2023-06-27 17:06 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +      |> Map.reject(fn {k, _v} -> k == :__unknown_fields__ end)
I'd use drop or pop here
```suggestion
      |> Map.drop([:__unknown_fields__])
```

2023-06-27 17:06 UTC, bblaszkow06 commented on lib/jellyfish/notification.ex
> +    |> Enum.reject(fn {k, _v} -> k in @discarded_fields end)
This round of review reminded me of `Map.drop`, it can be applied here as well
```suggestion
    |> Map.drop(@discarded_fields)
```

2023-06-28 10:08 UTC, LVala commented on lib/jellyfish/notifier.ex
> +        pids -> [pid | pids]
I think that this simple queue is enough as we can safely assume that responses from server will be in the same order as sent `RoomStateRequest` messages thanks to WebSockets.

2023-06-30 14:09 UTC, bblaszkow06 approved these changes

2023-06-30 14:09 UTC, bblaszkow06 commented on lib/jellyfish/notifier.ex
> +        pids -> [pid | pids]
Well, this assumption is much stronger - in addition to transport assuring the order, the backend must ensure the processing order. I can imagine async processing of "request" on the backend that would break it.

For now though it will be enough to document that assumption - please add a comment with that

2023-07-03 07:29 UTC, merged