Subscribing for events
jellyfish-dev/elixir_server_sdk pull request #19
Opened 2023-07-07 08:52 UTC by roznawsk

2023-07-10 13:14 UTC, LVala requested changes
I'll wait with the rest of the review because the reasons stated in comments.

2023-07-10 13:14 UTC, LVala commented on lib/jellyfish/notifier.ex
> +    with true <- event_type in @valid_events do
```suggestion
  def subscribe(notifier, event_type, room_id) when event_type in @valid_types do
```

2023-07-10 13:14 UTC, LVala commented on lib/jellyfish/notifier.ex
> +  @spec start_link(options()) :: {:ok, pid()} | {:error, term()}
Like I said, I think that this function shouldn't need to specify the events.

2023-07-11 07:36 UTC, roznawsk commented on lib/jellyfish/notifier.ex
> +  iex> {:ok, _rooms} = Jellyfish.Notifier.subscribe(notifier, :server_notifications, :all)
I like the current solution. We only send `SubscribeRequest` once, immediately after starting the notifier. For now I see a scenario, in which we define `Notifier` inside `Application` and pass the events we want to receive inside start options.
I don't see a scenario, when we would need to subscribe for some new event late after starting the notifier.

2023-07-11 07:48 UTC, roznawsk commented on lib/jellyfish/notifier.ex
> +  iex> {:ok, _rooms} = Jellyfish.Notifier.subscribe(notifier, :server_notifications, :all)
Whether specyfing `:server_notifications` is redundant - if Notifier is receiving more than one type of event, we have to specify what kind of events we want the calling process to subscribe to. I think the current way to do it (passing an atom representing certain event type) is the easiest from the user perspective.

2023-07-11 09:43 UTC, sgfn commented on lib/jellyfish/notifier.ex
>    WebSocket connection and receiving notifications form Jellyfish server.
```suggestion
  WebSocket connection and receiving notifications from Jellyfish server.
```

2023-07-11 09:43 UTC, sgfn commented on lib/jellyfish/notifier.ex
> +    with {:ok, events} <- Keyword.get(opts, :events, [:server_notification]) |> validate_events(),
If we don't decide to drop the `:events` option from `start` and `start_link`, I'd advocate for moving this logic into the `Utils.get_options_or_defaults` function

2023-07-11 09:43 UTC, sgfn commented on lib/jellyfish/notifier.ex
> +    end
```suggestion
    if Enum.all?(events, fn event -> event in @valid_events end) do
      events
      |> Enum.uniq()
      |> Enum.map(&to_proto_event_type/1)
      |> then(&{:ok, &1})
    else
      {:error, :invalid_event_type}
    end
```
Nitpick but we're not doing anything else in the `with` statement

2023-07-11 09:43 UTC, sgfn commented on test/test_helper.exs
> +# end
?

2023-07-11 09:43 UTC, sgfn commented on lib/jellyfish/notifier.ex
> +  def subscribe(notifier, event_type, room_id) do
Since we'll use this function to subscribe to other event types as well, and since the different requests may or may not contain different options, I'd say we might want to implement a solution like in `Jellyfish.Room.add_component` -- define separate modules with structs for different event types, as in `Jellyfish.Component.{HLS, RTSP}`, and allow the user to either pass the struct name (which means we'll use default options) or the struct with custom configuration.

2023-07-11 09:43 UTC, sgfn commented on lib/jellyfish/notifier.ex
> +  iex> {:ok, _rooms} = Jellyfish.Notifier.subscribe(notifier, :server_notifications, :all)
From what I understand, right now `start`ing the `Notifier` automatically subscribes us to the events passed as the options -- if we keep it this way, we should include a comment about it

At the moment, I feel like it's easy to confuse 1) sending a subscribe request to Jellyfish with 2) subscribing to receive events from the `Notifier` -- I think we should be more explicit about the distinction.

2023-07-11 15:24 UTC, sgfn commented on test/jellyfish/notifier_test.exs
> +    @tag :this
leftover?

2023-07-11 16:27 UTC, roznawsk commented on lib/jellyfish/notifier.ex
> +  iex> {:ok, _rooms} = Jellyfish.Notifier.subscribe(notifier, :server_notifications, :all)
As per Łukasz comment, it has been unified now - calling `Notifier.subscribe` will every time cause sending a `SubscribeRequest` message to Jellyfish.

2023-07-12 09:28 UTC, LVala requested changes
SMTG besides these small issues

2023-07-12 09:28 UTC, LVala commented on lib/jellyfish/notifier.ex
> +  @spec subscribe(notifier(), :server_notification, Room.id() | :all) ::
I would create `@type` for event types, then it can be easily extended.

2023-07-12 09:28 UTC, LVala commented on lib/jellyfish/notifier.ex
> +      {:error, _reason} = error -> error
Consider creating the request id here and match on it in `receive` block, then we are sure that the `{:jellyfish, {:subscribe_answer, answer}}` is intended for this `subscribe` call in an event when more that one process subscribes for notifications.

2023-07-12 09:28 UTC, LVala commented on .gitmodules
> +	branch = actually-subscribe-for-notifications
<sub>just a friendly reminder</sub>

2023-07-12 13:10 UTC, LVala approved these changes
👍

2023-07-12 13:26 UTC, mickel8 approved these changes

2023-07-12 13:59 UTC, merged