Hls playable
jellyfish-dev/elixir_server_sdk pull request #24
Opened 2023-07-24 15:51 UTC by Karolk99

2023-07-25 06:42 UTC, Rados13 commented on lib/jellyfish/component/hls.ex
> +  end
Shouldn't we return here this struct instead of a map?

2023-07-25 06:42 UTC, Rados13 commented on lib/jellyfish/component/hls.ex
> +  end
Or we should rename this to something like `metadata_from_proto`.

2023-07-25 06:42 UTC, Rados13 commented on lib/jellyfish/component/config.ex
I think that file should be renamed to `deserializer.ex`.

2023-07-25 06:42 UTC, Rados13 commented on test/jellyfish/room_test.exs
Shouldn't we add a test, which verifies whether we get a notification about changing the state of the HLS component to playable?

2023-07-25 08:42 UTC, Karolk99 commented on test/jellyfish/room_test.exs
It's impossible to do right now. In order to get `hlsplayable` message we have to connect peer with some kind of stream. If we simulate this message on the SDK side, the test will work until something changes on the Jellyfish side

2023-07-25 09:01 UTC, Rados13 commented on test/jellyfish/room_test.exs
Doesn't exist an RTSP server, which has got a docker container that we could use in such a test? Then we would add an RTSP component to receive stream from this server.
Something like this [image](https://hub.docker.com/r/easymile/ez-rtsp-server).

2023-07-25 09:57 UTC, LVala requested changes

2023-07-25 09:57 UTC, LVala commented on lib/jellyfish/component/hls.ex
> +  end
Do implemented callbacks show up in the documentation? If so, add `@doc false` everywhere.

2023-07-25 10:15 UTC, roznawsk approved these changes

2023-07-25 11:59 UTC, Karolk99 commented on lib/jellyfish/component/hls.ex
> +  end
They don't

2023-07-25 12:05 UTC, Karolk99 commented on test/jellyfish/room_test.exs
It's a great idea to implement in the future. Right now because of the h264 parser, we can't use both hls and rtsp components. When there is a new release of the h264 parser, we can write that test.

2023-07-26 08:26 UTC, LVala approved these changes

2023-07-26 10:24 UTC, merged