Use returned jellyfish address
jellyfish-dev/elixir_server_sdk pull request #28
Opened 2023-08-23 07:37 UTC by Rados13

Adjust elixir server SDK to changes in [this PR](https://github.com/jellyfish-dev/jellyfish/pull/57).

2023-08-24 09:01 UTC, LVala approved these changes

2023-08-24 09:04 UTC, LVala commented
Just realised, you have to update examples in `README.md`, where `Jellyfish.create` is used.

2023-08-24 11:49 UTC, sgfn requested changes
Please update the docs (e.g. [here](https://jellyfish-dev.github.io/jellyfish-docs/getting_started/authentication), maybe some other places if there are any)

If you can, please update `examples/` in Jellyfish as well

2023-08-24 11:49 UTC, sgfn commented on lib/jellyfish/room.ex
You need to update the example in moduledoc of this file

2023-08-25 08:19 UTC, Rados13 commented
Example in Jellyfish updated https://github.com/jellyfish-dev/jellyfish/pull/73 
The only occurrence of Room creation in jellyfish docs also updated https://github.com/jellyfish-dev/jellyfish-docs/pull/21
A function for updating the server address in the client also was added.

2023-08-25 09:21 UTC, sgfn approved these changes
🥇

2023-08-25 09:21 UTC, sgfn commented on lib/jellyfish/room.ex
>    ```
The doctest is a nice addition, but isn't it a bit too complicated to be used as an example? I think the previous version was more readable

2023-08-25 09:29 UTC, Rados13 commented on lib/jellyfish/room.ex
>    ```
Yup, the previous version was more readable, but the doctest prevents example from being outdated. I can remove these additional checks and leave only asserts so it will be a little bit less complicated. It would look like this
```suggestion
  iex> client = Jellyfish.Client.new()
  iex> assert {:ok, %Jellyfish.Room{
  ...>    components: [],
  ...>    config: %{max_peers: 10, video_codec: nil},
  ...>    peers: []
  ...>  } = room, _jellyfish_address} = Jellyfish.Room.create(client, max_peers: 10)
  iex> assert {:ok,%Jellyfish.Peer{
  ...>    status: :disconnected,
  ...>    type: Jellyfish.Peer.WebRTC
  ...> } = peer, _peer_token} = Jellyfish.Room.add_peer(client, room.id, Jellyfish.Peer.WebRTC)
```

2023-08-25 10:09 UTC, sgfn commented on lib/jellyfish/room.ex
>    ```
For me, it's fine either way. You decide

2023-08-25 14:55 UTC, LVala approved these changes

2023-08-25 14:55 UTC, LVala commented on test/jellyfish/client_test.exs
> +           } = client
I know that's what I did in other tests (couldn't really think of other way), but asserting on `Tesla`'s internal structures is a code smell. I would at least match on the least amount of fields (the `JSON` or `adapter:` parts are really not necessary here). Don't repeat my mistakes 😃, for now you can leave as it to take care of the whole module some other time, up to you.

2023-08-29 08:13 UTC, merged