RTC 386
jellyfish-dev/elixir_server_sdk pull request #37
Opened 2023-10-16 11:26 UTC by Rados13

Related to: https://github.com/jellyfish-dev/jellyfish/pull/104

2023-10-23 10:03 UTC, LVala requested changes

2023-10-23 10:03 UTC, LVala commented on mix.exs
> +      Mix.Task.run("test")
I think there should be some kind of disclaimer that some of the tests will not pass without the docker, at least. In general I'm not sure about the "tests only in docker" thing, but I guess otherwise you would need to run the Jellyfish yourself or hack the docker-compose to allow the container to access host's `localhost`, so I'm not complaining. Maybe an option to run without docker at all instead of the fallback?

2023-10-23 10:56 UTC, Rados13 commented on test/jellyfish/notifier_test.exs
> +  @webhook_url "http://172.28.0.2:#{@webhook_port}/"
I tried a few different approaches to do that because I hate docker networking, but it always doesn't work. In jellyfish, I received that sending a request on domain `http://test:4000/` failed with reason `:nxdomain`. I read somewhere there is a possibility that this is because the `test` container doesn't register as healthy so it doesn't register its alias in internal Docker DNS, so we couldn't refer to it by alias in jellyfish.

2023-10-23 11:00 UTC, Rados13 commented on lib/jellyfish/notifier.ex
> +  end
I thought about moving this function to the Notification module, but then I found out that Notification is a private module and isn't available in docs. I wasn't sure if we wanted to change it, so I decided to leave it in Notifier as it is an alternative to Notifier. As for the other suggestions, I will apply them, and sorry I forgot about docs 😅 .

2023-10-23 11:16 UTC, Rados13 commented on mix.exs
> +      Mix.Task.run("test")
I didn't think about it as a fallback and more like a code that is run inside a docker container, but this log is very misleading 😓 .

2023-10-23 11:18 UTC, Rados13 commented on mix.exs
> +      Mix.Task.run("test")
As for running tests without docker, I can create an alias for running tests without docker.

2023-10-23 12:07 UTC, LVala commented on lib/jellyfish/notifier.ex
> +  end
I think I would make it public tbh, but that's not a big issue tbh.

2023-10-23 13:44 UTC, mickel8 requested changes
Could we add an option to easily run tests using Jellyfish that runs locally? Something like `mix test.local`?

2023-10-23 13:44 UTC, mickel8 commented on test/jellyfish/notifier_test.exs
> +  @webhook_url "http://172.28.0.2:#{@webhook_port}/"
I think that's because of calling `docker compose run` instead of `docker compose up`. 

```yaml
version: "3"

services:
  jellyfish:
    extends:
      file: docker-compose-dev.yaml
      service: jellyfish
    environment:
      - JF_HOST=jellyfish:5002

  test:
    image: hexpm/elixir:1.14.4-erlang-25.3.2-alpine-3.16.5
    container_name: test
    command: sh -c "cd app/ && apk add git && mix local.hex --force && mix local.rebar --force && mix deps.get && mix coveralls.json --warnings-as-errors"
    environment:
      - MIX_ENV=integration_test
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      jellyfish:
        condition: service_healthy
 ```
 
 When you change webhook_url in tests to `test:4000` and run `docker compose up` with the above docker compose yaml, all tests are passing correctly

2023-10-23 13:44 UTC, mickel8 commented on mix.exs
> +      stream_command(docker_compose_prefix ++ ["run", "--remove-orphans", "test"])
Would be nice to do some cleanup at the end. You can try with `docker compose -f docker-compose-test.yaml stop` and `docker compose -f docker-compose-test.yaml rm -f`

2023-10-23 14:14 UTC, mickel8 commented on lib/jellyfish/notifier.ex
> +  end
You mean you would like to make Notification public and move the function there, right?  Sounds good too

2023-10-24 06:30 UTC, Rados13 commented on test/jellyfish/notifier_test.exs
> +  @webhook_url "http://172.28.0.2:#{@webhook_port}/"
Yeah, you are right. I forgot that it is possible to use `docker compose up` with a specific `service_name` 😅 . One downside I see with using `docker compose up` is that, by default, it prints logs from all services, including jellyfish. I changed the network configuration in docker-compose according to your suggestion.

2023-10-24 06:41 UTC, LVala commented on lib/jellyfish/webhook_notifier.ex
> +  def receive(json) do
I'm not sure if this is intentional, but maybe let's move the alias to the top of the module, just after `@moduledoc`?

2023-10-24 06:41 UTC, LVala commented on mix.exs
> +      "test.local": ["test --without_docker"]
Nitpick, why not something like `&test_local/1`? The `test --without_docker` seems kinda unnecessary when you have the `mix test.local` function.

2023-10-24 06:41 UTC, LVala commented on mix.exs
> +        System.put_env("WEBHOOK_ADDRESS", "127.0.0.1")
I would probably use `Application.put_env`, but that's a nitpick.

2023-10-24 06:41 UTC, LVala commented on mix.exs
> +        Mix.Task.run("test", ["--exclude", "doctest"])
I'm not sure why we exclude the doctests?

2023-10-24 06:45 UTC, Rados13 commented on lib/jellyfish/webhook_notifier.ex
> +  def receive(json) do
But this alias is just after `@moduledoc` 😕 .

2023-10-24 06:55 UTC, Rados13 commented on mix.exs
> +      "test.local": ["test --without_docker"]
If we try to use `Mix.Task.run("test")` in a different function than `test_in_docker`, then it will use the defined by us `test` alias instead of the standard `test`.

2023-10-24 07:14 UTC, Rados13 commented on mix.exs
> +        Mix.Task.run("test", ["--exclude", "doctest"])
To make it work locally [this `doctest`](https://github.com/jellyfish-dev/elixir_server_sdk/blob/5cbd0dbdf65eebc1f54b9b52682ab5087ac8d34f/lib/jellyfish/room.ex#L5-L31) we would have to pass a proper `server_address` based on that in what environment we run tests.

2023-10-24 07:23 UTC, Rados13 commented on mix.exs
> +        System.put_env("WEBHOOK_ADDRESS", "127.0.0.1")
You would like that instead of `System.put_env("SERVER_ADDRESS", "127.0.0.1:5002")` we would do something like  that`Application.put_env(:jellyfish_server_sdk, :local_server_address, "127.0.0.1:5002")`?

2023-10-24 10:35 UTC, LVala approved these changes

2023-10-24 14:41 UTC, Karolk99 approved these changes

2023-10-24 19:35 UTC, mickel8 approved these changes

2023-10-25 07:24 UTC, Rados13 commented on .circleci/config.yml
> +      - run: docker compose -f docker-compose-test.yaml up test
I'm unsure if we can not add a test because without this command, it doesn't exit after the tests finish. [Example run of `docker compose -f docker-compose-test.yaml up` on CircleCI](https://app.circleci.com/pipelines/github/jellyfish-dev/elixir_server_sdk/313/workflows/637eef59-008a-4cca-8a40-a21bbc8b1526/jobs/947). But this is great issue because by that I remembered why did we use `docker compose run` previously. Command `docker compose up` doesn't return exit code from container execution, which results in that tests could fail and CI still would be green [example run with failing test with `docker compose up test`](https://app.circleci.com/pipelines/github/jellyfish-dev/elixir_server_sdk/314/workflows/da23865b-e01a-454e-ae7e-e46aedd61bd7/jobs/952). But this means I have to return most of the changes in docker-compose configuration 😞 .

2023-10-26 07:45 UTC, merged