[RTC-220] Server notifications
jellyfish-dev/elixir_server_sdk pull request #8
Opened 2023-04-20 14:12 UTC by LVala

No test have beeen written yet, partially because of the discussion whether to use Jellyfish instance to test instead of mocks. Everything besides this should be good to CR.

2023-04-20 15:48 UTC, mickel8 requested changes

2023-04-20 15:48 UTC, mickel8 commented on lib/jellyfish/notifier.ex
> +          Process.exit(pid, :normal)
You don't need to exit the process as it is already terminating.

We for sure need to monitor pid in case of WebSockex crashes. The question is if monitoring a process is enough i.e. maybe we could resign from sending a dedicated message?

2023-04-20 15:48 UTC, mickel8 commented on lib/jellyfish/notifier.ex
> +        Process.link(pid)
Instead of linking manually, use WebSockex.start_link. You can make use of `apply` function from Elixir

2023-04-20 15:48 UTC, mickel8 commented on lib/jellyfish/notifier.ex
> +      {:ok, %{type: decoded_type, room_id: room_id, id: id}}
I would favor a tuple

2023-04-20 15:48 UTC, mickel8 commented on test/jellyfish/client_test.exs
>               } = client
Honestly speaking I am not sure about checking Client structure. I don't feel like this is a valid test :thinking:

2023-04-21 08:19 UTC, LVala commented on test/jellyfish/client_test.exs
>               } = client
Do you mean this test specifically, or checking the `Client` struct in general? I don't thing we can do much more here without the Jellyfish itself, also it tests logic responsible for adding protocol prefix to the address.

2023-04-21 08:39 UTC, LVala commented on lib/jellyfish/notifier.ex
> +          Process.exit(pid, :normal)
WDYM resign from sending a dedicated message? I can add a dedicated notification when WebSocket connection is dropped, but idk if that's what you mean.

2023-04-21 10:46 UTC, mickel8 approved these changes

2023-04-21 10:49 UTC, merged