[RTC-192] RTSP component + small refactor
jellyfish-dev/elixir_server_sdk pull request #9
Opened 2023-04-24 10:59 UTC by sgfn

This PR introduces breaking changes to the creation of components

2023-04-28 18:19 UTC, mickel8 approved these changes

2023-05-04 07:44 UTC, LVala commented on lib/jellyfish/component.ex
> +      %RTSP{} -> "rtsp"
If we are making breaking changes, maybe we should also change these strings with component/peer names to atoms (before strings were used, as it was Jellyfish responsibility to check if they are valid).

2023-05-04 13:35 UTC, sgfn commented on lib/jellyfish/component.ex
> +      %RTSP{} -> "rtsp"
I'm not sure I see the point of doing that -- I mean, we'd have to convert the atom to a string (in the only place the function's used in, `lib/jellyfish/room.ex:173`) anyway...

2023-05-04 13:51 UTC, LVala commented on lib/jellyfish/component.ex
> +      %RTSP{} -> "rtsp"
Sorry, I didn't mean to highlight this part of the code (I don't know why I did, seems kind of random now). What I meant is that we still pass `"webrtc"` string to `add_peer` function as a type, maybe, to be consistent, we should also validate if the type is correct on sdk side (like we do with components) and with that, use at least atoms instead of strings (as we don't expect to pass any options for peers at the moment, we could thing about that tho).

2023-05-05 13:39 UTC, LVala requested changes

2023-05-05 13:39 UTC, LVala commented on lib/jellyfish/component.ex
> +  @spec type_from_options(struct()) :: atom()
```suggestion
  @spec type_from_options(struct()) :: type()
```

2023-05-05 13:39 UTC, LVala commented on lib/jellyfish/component.ex
> +  @spec type_from_string(String.t()) :: atom()
```suggestion
  @spec type_from_string(String.t()) :: type()
```

2023-05-05 13:39 UTC, LVala commented on lib/jellyfish/peer.ex
> +  @spec type_from_string(String.t()) :: atom()
```suggestion
  @spec type_from_string(String.t()) :: type()
```

2023-05-05 13:39 UTC, LVala commented on lib/jellyfish/component.ex
> +      else: raise("Invalid component type string")
By convention, we call `raise` without parentheses (as you did in some other places).

2023-05-05 13:39 UTC, LVala commented on lib/jellyfish/component/rtsp.ex
> +        }
Noticed it only now, you should use `snake_case` here and create a function that converts it to `camelCase` like we do e.g. [here](https://github.com/jellyfish-dev/jellyfish/blob/main/lib/jellyfish_web/controllers/room_json.ex). Hope that won't be an issue anymore when we move to protobufs.

2023-05-08 08:37 UTC, mickel8 commented on lib/jellyfish/component.ex
> +      %RTSP{} -> "rtsp"
Let's unify peers with components and always pass struct or a module. If module is passed we assume default options. This means that both of the following options should be accepted

```elixir
Room.add_component(client, room_id, HLS)
Room.add_component(client, room_id, %HLS{})
```

Sorry for not spotting this at the first time :slightly_frowning_face:

2023-05-08 08:39 UTC, mickel8 requested changes

2023-05-08 08:39 UTC, mickel8 commented on test/jellyfish/room_test.exs
> +    defstruct [:abc, :xdd]
xdd sounds a little unprofessional :stuck_out_tongue:

2023-05-08 10:03 UTC, sgfn commented on lib/jellyfish/component.ex
> +      else: raise("Invalid component type string")
I'm blaming `mix format` for this :PP

2023-05-08 11:15 UTC, sgfn commented on lib/jellyfish/component.ex
> +      else: raise("Invalid component type string")
Yeah, it keeps adding the parentheses -- I'm afraid the mighty linter has spoken...

I guess the convention doesn't apply when using keyword list if syntax ¯\_(ツ)_/¯

2023-05-08 12:03 UTC, LVala approved these changes
👍

2023-05-09 09:04 UTC, mickel8 approved these changes

2023-05-09 09:50 UTC, merged